### ISSUE TITLE
ARCC Name on Front Page

### ISSUE THREAD

**Issue by JT003** [JHS-ARCC-Club/arcc-website#1]
Current: Jesuit High school Autonomous Car Club (ARCC)
Suggest: Jesuit High School Autonomous Race Car Club (ARCC) 
* capitalize S in school
* add the word "Race"

**Comment by JT003** [comment]
2nd Suggest: take out "Jesuit High School" from the official name title
* still use Jesuit High School as in "Michael Equi '20 and Caelin Sutch '20 of Jesuit High Scool, Carmichael, California.

**Comment by caelinsutch** [comment]
Fixed, pending release
