### ISSUE TITLE
Meet Our Club Members - Mr. Tsai Moderator

### ISSUE THREAD

**Issue by JT003** [JHS-ARCC-Club/arcc-website#4]
Suggest: Take me out of the website to reflect the full scope of your work and accomplishment - not a hint of some adults guiding/helping you.

Suggest: Use "Team" not "Club" to project a higher level of organization.

Suggest: Use "COO" instead of "Marketing & Mgmt" for Caelin's title

**Comment by caelinsutch** [comment]
Fixed, pending release
