### ISSUE TITLE
JHS Address as Address of ARCC

### ISSUE THREAD

**Issue by JT003** [JHS-ARCC-Club/arcc-website#5]
Current: 1200 Jacob Lane Carmichael, CA. 95608

Suggest: Delete the address and replace with either Michael or Caelin home address. Or leave physical address completely out of the website. There is really no need for a physical address these days. If there is a need for a physical address, add another layer of separation by using a PO box. Once you have secured the domain name and enabled forwarding, just use a generic email such as support@arcc.ai as the main point of contact.

**Comment by caelinsutch** [comment]
Fixed
